package com.cst.cstpaysdk.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cst.cstpaysdk.db.entity.CardInfoEntity;
import com.cst.cstpaysdk.db.entity.EquipmentCreditEntity;
import com.cst.cstpaysdk.db.entity.FaceInfoEntity;
import com.cst.cstpaysdk.db.entity.TradeRecordEntity;
import com.cst.cstpaysdk.db.entity.UserCreditEntity;

import com.cst.cstpaysdk.db.CardInfoEntityDao;
import com.cst.cstpaysdk.db.EquipmentCreditEntityDao;
import com.cst.cstpaysdk.db.FaceInfoEntityDao;
import com.cst.cstpaysdk.db.TradeRecordEntityDao;
import com.cst.cstpaysdk.db.UserCreditEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardInfoEntityDaoConfig;
    private final DaoConfig equipmentCreditEntityDaoConfig;
    private final DaoConfig faceInfoEntityDaoConfig;
    private final DaoConfig tradeRecordEntityDaoConfig;
    private final DaoConfig userCreditEntityDaoConfig;

    private final CardInfoEntityDao cardInfoEntityDao;
    private final EquipmentCreditEntityDao equipmentCreditEntityDao;
    private final FaceInfoEntityDao faceInfoEntityDao;
    private final TradeRecordEntityDao tradeRecordEntityDao;
    private final UserCreditEntityDao userCreditEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardInfoEntityDaoConfig = daoConfigMap.get(CardInfoEntityDao.class).clone();
        cardInfoEntityDaoConfig.initIdentityScope(type);

        equipmentCreditEntityDaoConfig = daoConfigMap.get(EquipmentCreditEntityDao.class).clone();
        equipmentCreditEntityDaoConfig.initIdentityScope(type);

        faceInfoEntityDaoConfig = daoConfigMap.get(FaceInfoEntityDao.class).clone();
        faceInfoEntityDaoConfig.initIdentityScope(type);

        tradeRecordEntityDaoConfig = daoConfigMap.get(TradeRecordEntityDao.class).clone();
        tradeRecordEntityDaoConfig.initIdentityScope(type);

        userCreditEntityDaoConfig = daoConfigMap.get(UserCreditEntityDao.class).clone();
        userCreditEntityDaoConfig.initIdentityScope(type);

        cardInfoEntityDao = new CardInfoEntityDao(cardInfoEntityDaoConfig, this);
        equipmentCreditEntityDao = new EquipmentCreditEntityDao(equipmentCreditEntityDaoConfig, this);
        faceInfoEntityDao = new FaceInfoEntityDao(faceInfoEntityDaoConfig, this);
        tradeRecordEntityDao = new TradeRecordEntityDao(tradeRecordEntityDaoConfig, this);
        userCreditEntityDao = new UserCreditEntityDao(userCreditEntityDaoConfig, this);

        registerDao(CardInfoEntity.class, cardInfoEntityDao);
        registerDao(EquipmentCreditEntity.class, equipmentCreditEntityDao);
        registerDao(FaceInfoEntity.class, faceInfoEntityDao);
        registerDao(TradeRecordEntity.class, tradeRecordEntityDao);
        registerDao(UserCreditEntity.class, userCreditEntityDao);
    }
    
    public void clear() {
        cardInfoEntityDaoConfig.clearIdentityScope();
        equipmentCreditEntityDaoConfig.clearIdentityScope();
        faceInfoEntityDaoConfig.clearIdentityScope();
        tradeRecordEntityDaoConfig.clearIdentityScope();
        userCreditEntityDaoConfig.clearIdentityScope();
    }

    public CardInfoEntityDao getCardInfoEntityDao() {
        return cardInfoEntityDao;
    }

    public EquipmentCreditEntityDao getEquipmentCreditEntityDao() {
        return equipmentCreditEntityDao;
    }

    public FaceInfoEntityDao getFaceInfoEntityDao() {
        return faceInfoEntityDao;
    }

    public TradeRecordEntityDao getTradeRecordEntityDao() {
        return tradeRecordEntityDao;
    }

    public UserCreditEntityDao getUserCreditEntityDao() {
        return userCreditEntityDao;
    }

}
