package com.cst.cstpaysdk.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cst.cstpaysdk.db.entity.FaceInfoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FACE_INFO_ENTITY".
*/
public class FaceInfoEntityDao extends AbstractDao<FaceInfoEntity, Long> {

    public static final String TABLENAME = "FACE_INFO_ENTITY";

    /**
     * Properties of entity FaceInfoEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RecordId = new Property(1, String.class, "recordId", false, "RECORD_ID");
        public final static Property UserId = new Property(2, String.class, "userId", false, "USER_ID");
        public final static Property UserCode = new Property(3, String.class, "userCode", false, "USER_CODE");
        public final static Property UserName = new Property(4, String.class, "userName", false, "USER_NAME");
        public final static Property Sex = new Property(5, String.class, "sex", false, "SEX");
        public final static Property UserType = new Property(6, String.class, "userType", false, "USER_TYPE");
        public final static Property UserDept = new Property(7, String.class, "userDept", false, "USER_DEPT");
        public final static Property Data = new Property(8, String.class, "data", false, "DATA");
        public final static Property OperateType = new Property(9, String.class, "operateType", false, "OPERATE_TYPE");
        public final static Property RecordTime = new Property(10, String.class, "recordTime", false, "RECORD_TIME");
    }


    public FaceInfoEntityDao(DaoConfig config) {
        super(config);
    }
    
    public FaceInfoEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FACE_INFO_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RECORD_ID\" TEXT," + // 1: recordId
                "\"USER_ID\" TEXT UNIQUE ," + // 2: userId
                "\"USER_CODE\" TEXT UNIQUE ," + // 3: userCode
                "\"USER_NAME\" TEXT," + // 4: userName
                "\"SEX\" TEXT," + // 5: sex
                "\"USER_TYPE\" TEXT," + // 6: userType
                "\"USER_DEPT\" TEXT," + // 7: userDept
                "\"DATA\" TEXT," + // 8: data
                "\"OPERATE_TYPE\" TEXT," + // 9: operateType
                "\"RECORD_TIME\" TEXT);"); // 10: recordTime
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_FACE_INFO_ENTITY_RECORD_ID ON \"FACE_INFO_ENTITY\"" +
                " (\"RECORD_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FACE_INFO_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FaceInfoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String recordId = entity.getRecordId();
        if (recordId != null) {
            stmt.bindString(2, recordId);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
 
        String userCode = entity.getUserCode();
        if (userCode != null) {
            stmt.bindString(4, userCode);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(5, userName);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(6, sex);
        }
 
        String userType = entity.getUserType();
        if (userType != null) {
            stmt.bindString(7, userType);
        }
 
        String userDept = entity.getUserDept();
        if (userDept != null) {
            stmt.bindString(8, userDept);
        }
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(9, data);
        }
 
        String operateType = entity.getOperateType();
        if (operateType != null) {
            stmt.bindString(10, operateType);
        }
 
        String recordTime = entity.getRecordTime();
        if (recordTime != null) {
            stmt.bindString(11, recordTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FaceInfoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String recordId = entity.getRecordId();
        if (recordId != null) {
            stmt.bindString(2, recordId);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
 
        String userCode = entity.getUserCode();
        if (userCode != null) {
            stmt.bindString(4, userCode);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(5, userName);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(6, sex);
        }
 
        String userType = entity.getUserType();
        if (userType != null) {
            stmt.bindString(7, userType);
        }
 
        String userDept = entity.getUserDept();
        if (userDept != null) {
            stmt.bindString(8, userDept);
        }
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(9, data);
        }
 
        String operateType = entity.getOperateType();
        if (operateType != null) {
            stmt.bindString(10, operateType);
        }
 
        String recordTime = entity.getRecordTime();
        if (recordTime != null) {
            stmt.bindString(11, recordTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FaceInfoEntity readEntity(Cursor cursor, int offset) {
        FaceInfoEntity entity = new FaceInfoEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // recordId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // userCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // userName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sex
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // userType
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // userDept
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // data
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // operateType
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // recordTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FaceInfoEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRecordId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUserName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSex(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUserType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUserDept(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setData(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setOperateType(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setRecordTime(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FaceInfoEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FaceInfoEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FaceInfoEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
