package com.cst.cstpaysdk.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cst.cstpaysdk.db.entity.UserCreditEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_CREDIT_ENTITY".
*/
public class UserCreditEntityDao extends AbstractDao<UserCreditEntity, Long> {

    public static final String TABLENAME = "USER_CREDIT_ENTITY";

    /**
     * Properties of entity UserCreditEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property UserCode = new Property(2, String.class, "userCode", false, "USER_CODE");
        public final static Property UserName = new Property(3, String.class, "userName", false, "USER_NAME");
        public final static Property OfflinePayNum = new Property(4, int.class, "offlinePayNum", false, "OFFLINE_PAY_NUM");
        public final static Property OfflinePayAmount = new Property(5, String.class, "offlinePayAmount", false, "OFFLINE_PAY_AMOUNT");
    }


    public UserCreditEntityDao(DaoConfig config) {
        super(config);
    }
    
    public UserCreditEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_CREDIT_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: userId
                "\"USER_CODE\" TEXT," + // 2: userCode
                "\"USER_NAME\" TEXT," + // 3: userName
                "\"OFFLINE_PAY_NUM\" INTEGER NOT NULL ," + // 4: offlinePayNum
                "\"OFFLINE_PAY_AMOUNT\" TEXT);"); // 5: offlinePayAmount
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_USER_CREDIT_ENTITY_USER_ID ON \"USER_CREDIT_ENTITY\"" +
                " (\"USER_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_CREDIT_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserCreditEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String userCode = entity.getUserCode();
        if (userCode != null) {
            stmt.bindString(3, userCode);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(4, userName);
        }
        stmt.bindLong(5, entity.getOfflinePayNum());
 
        String offlinePayAmount = entity.getOfflinePayAmount();
        if (offlinePayAmount != null) {
            stmt.bindString(6, offlinePayAmount);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserCreditEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String userCode = entity.getUserCode();
        if (userCode != null) {
            stmt.bindString(3, userCode);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(4, userName);
        }
        stmt.bindLong(5, entity.getOfflinePayNum());
 
        String offlinePayAmount = entity.getOfflinePayAmount();
        if (offlinePayAmount != null) {
            stmt.bindString(6, offlinePayAmount);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserCreditEntity readEntity(Cursor cursor, int offset) {
        UserCreditEntity entity = new UserCreditEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // userName
            cursor.getInt(offset + 4), // offlinePayNum
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // offlinePayAmount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserCreditEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOfflinePayNum(cursor.getInt(offset + 4));
        entity.setOfflinePayAmount(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserCreditEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserCreditEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserCreditEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
